Update DevActions.yml
Copied from MoodleHQ repo

diff --git a/.github/workflows/DevActions.yml b/.github/workflows/DevActions.yml
--- a/.github/workflows/DevActions.yml
+++ b/.github/workflows/DevActions.yml
@@ -1,56 +1,144 @@
-name: DevActions
+name: Moodle Coding Style Tests
 
-on:
-  push:
-    branches:
-      - main    # Only run on push to the 'main' branch
-  pull_request:
-    branches:
-      - main    # Optionally, you can trigger on pull requests as well
+on: [push, pull_request]
 
 jobs:
-  build:
-    runs-on: windows-latest    # Specify that the job runs on the Windows environment
+  test:
+    runs-on: ${{ matrix.os }}
 
+    strategy:
+      fail-fast: false
+      matrix:
+        php:
+          - 8.3
+          - 8.2
+          - 8.1
+          - 8.0
+          - 7.4
+        os:
+          - ubuntu-latest
+          - windows-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2    # This action checks out the code from your repository
+      - name: Set git to use LF
+        run: |
+          git config --global core.autocrlf false
+          git config --global core.eol lf
 
-      - name: Setup PHP
+      - name: Check out repository code
+        uses: actions/checkout@v4
+
+      - name: Setup PHP ${{ matrix.php }}
         uses: shivammathur/setup-php@v2
         with:
-          php-version: 8.0 # change to fit our moodle version
-          extensions: mbstring, intl, curl, xml, zip, soap, gd, mysqli
-          ini-values: memory_limit=512M, post_max_size=100M, upload_max_filesize=100M
+          php-version: ${{ matrix.php }}
+          extensions: ${{ matrix.extensions }}
+          ini-values: pcov.directory=moodle, error_reporting=-1, display_errors=On
+          coverage: pcov
+          tools: composer
 
-      - name: Install Composer dependencies
+      - name: Install composer dependencies
         run: |
-          composer global config minimum-stability dev
-          composer global require moodlehq/moodle-cs
+          composer install
 
-
-      - name: Install mysql
+      - name: Run phplint
+        if: ${{ !cancelled() }}
         run: |
-          choco install mysql --version=5.7.31 -y
-          Start-Service MySQL
-          mysql --version
-          mysql -u root -e "CREATE DATABASE moodle_test;"
-          mysql -u root -e "CREATE USER 'moodleuser'@'localhost' IDENTIFIED BY 'password';"
-          mysql -u root -e "GRANT ALL PRIVILEGES ON moodle_test.* TO 'moodleuser'@'localhost';"
-          mysql -u root -e "FLUSH PRIVILEGES;"
-      
-      
-      - name: moodle installation
+          ./vendor/bin/phplint
+
+      - name: PHP Copy/Paste Detector
+        if: ${{ !cancelled() }}
+        run: ./vendor/bin/phpcpd --exclude moodle/Tests moodle
+
+      - name: Coding style
+        if: ${{ !cancelled() }}
+        run: ./vendor/bin/phpcs -ps .
+
+      - name: Run phpunit
+        if: ${{ !cancelled() }}
         run: |
-          copy config-dist.php config.php
-          (gc config.php) -replace 'your_database_name', 'moodle_test' | sc config.php
-          (gc config.php) -replace 'username', 'moodleuser' | sc config.php
-          (gc config.php) -replace 'password', 'password' | sc config.php
-          # Set other configuration variables as needed.
-          php admin\cli\install_database.php --agree-license --adminpass=adminpassword
+          ./vendor/bin/phpunit --coverage-text
 
+      - name: Test coverage
+        if: ${{ !cancelled() }}
+        run: ./vendor/bin/phpunit-coverage-check -t 80 clover.xml
 
-      # Tests will be specified here: (Php-unit)
-      - name: Run tests
-       #run: insert path for test folder
+      - name: Integration tests
+        if: ${{ !cancelled() && matrix.os == 'ubuntu-latest' }}
+        run: |
+          # There is one failure (exit with error 2, because some are fixable).
+          expectedcode=2
+          vendor/bin/phpcs --standard=moodle moodle/Tests/fixtures/integration_test_ci.php | tee output.txt
+          exitcode="${PIPESTATUS[0]}"
+          if [[ "${exitcode}" = "${expectedcode}" ]]; then
+              echo "Ok, got expected ${exitcode} exit code."
+          else
+              echo "Error: Expected ${expectedcode}, got ${exitcode} exit code."
+              exit 1
+          fi
+          grep -q  "PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY" output.txt
+
+          # The failure is fixed (exit with error 1, because all fixable ones were fixed).
+          expectedcode=1
+          vendor/bin/phpcbf --standard=moodle moodle/Tests/fixtures/integration_test_ci.php | tee output.txt
+          exitcode="${PIPESTATUS[0]}"
+          if [[ "${exitcode}" = "${expectedcode}" ]]; then
+              echo "Ok, got expected ${exitcode} exit code."
+          else
+              echo "Error: Expected ${expectedcode}, got ${exitcode} exit code."
+              exit 1
+          fi
+          grep -q "A TOTAL OF 1 ERROR WERE FIXED IN 1 FILE" output.txt
+
+          # So, there isn't any failure any more (exit without error, aka, 0)
+          expectedcode=0
+          vendor/bin/phpcs --standard=moodle moodle/Tests/fixtures/integration_test_ci.php | tee output.txt
+          exitcode="${PIPESTATUS[0]}"
+          if [[ "${exitcode}" = "${expectedcode}" ]]; then
+              echo "Ok, got expected ${exitcode} exit code."
+          else
+              echo "Error: Expected ${expectedcode}, got ${exitcode} exit code."
+              exit 1
+          fi
+
+      - name: Mark cancelled jobs as failed
+        if: ${{ cancelled() }}
+        run: exit 1
+
+  coverage:
+    if: github.repository == 'moodlehq/moodle-cs'
+    name: Code coverage (codecov)
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4
+
+      - name: Setup PHP 8.2
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: 8.2
+          ini-values: pcov.directory=moodle, error_reporting=-1, display_errors=On
+          coverage: pcov
+          tools: composer
+
+      - name: Install composer dependencies
+        run: |
+          composer install
+
+      - name: Run phpunit
+        if: ${{ !cancelled() }}
+        run: |
+          ./vendor/bin/phpunit --coverage-clover clover.xml
+
+      - name: Upload coverage
+        if: ${{ !cancelled() }}
+        uses: codecov/codecov-action@v4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: clover.xml
+          verbose: true
+
+      - name: Mark cancelled jobs as failed
+        if: ${{ cancelled() }}
+        run: exit 1
       
